[profile.default]
# Foundry configuration for CRE CLI
# This ensures consistent behavior across all environments

# Solidity compiler version (if needed for contract compilation)
solc_version = "0.8.24"

# Gas limit for transactions
gas_limit = 9223372036854775807

# Gas price for transactions  
gas_price = 3000000000

# Chain ID for local testing
chain_id = 31337

# RPC endpoint for tests
eth_rpc_url = "http://localhost:8545"

# Verbosity level
verbosity = 2

# Cache settings
cache = true
cache_path = "cache"
out = "out"

# Test settings
test_pattern = "test"
