// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package my_project

// Account discriminators
var (
	Account_DataAccount = [8]byte{85, 240, 182, 158, 76, 7, 18, 233}
)

// Event discriminators
var (
	Event_AccessLogged = [8]byte{243, 53, 225, 71, 64, 120, 109, 25}
	Event_DataUpdated  = [8]byte{110, 104, 69, 204, 253, 168, 30, 91}
)

// Instruction discriminators
var (
	Instruction_GetInputData = [8]byte{30, 17, 181, 230, 219, 1, 5, 138}
	Instruction_Initialize   = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_LogAccess    = [8]byte{196, 55, 194, 24, 5, 224, 161, 204}
	Instruction_UpdateData   = [8]byte{62, 209, 63, 231, 204, 93, 148, 123}
)
