// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package my_project

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
	solana "github.com/smartcontractkit/cre-cli/cmd/generate-bindings/solana_bindings/cre-sdk-go/capabilities/blockchain/solana"
	bindings "github.com/smartcontractkit/cre-cli/cmd/generate-bindings/solana_bindings/cre-sdk-go/capabilities/blockchain/solana/bindings"
	types "github.com/smartcontractkit/cre-cli/cmd/generate-bindings/solana_bindings/cre-sdk-go/types"
	cre "github.com/smartcontractkit/cre-sdk-go/cre"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_AccessLogged:
		value := new(AccessLogged)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as AccessLogged: %w", err)
		}
		return value, nil
	case Event_DataUpdated:
		value := new(DataUpdated)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DataUpdated: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_AccessLogged(eventData []byte) (*AccessLogged, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_AccessLogged {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_AccessLogged, binary.FormatDiscriminator(discriminator))
	}
	event := new(AccessLogged)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type AccessLogged: %w", err)
	}
	return event, nil
}

func (c *Codec) DecodeAccessLogged(event *solana.Log) (*AccessLogged, error) {
	res, err := ParseEvent_AccessLogged(event.Data)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type AccessLoggedTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
	contract *MyProject
}

func (t *AccessLoggedTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[AccessLogged], error) {
	decoded, err := t.contract.Codec.DecodeAccessLogged(l)
	if err != nil {
		return nil, err
	}
	return &bindings.DecodedLog[AccessLogged]{
		Data: *decoded,
		Log:  l,
	}, nil
}

func (c *MyProject) LogTrigger_AccessLogged(chainSelector uint64, subKeyPathAndValue []solana.SubKeyPathAndFilter) (cre.Trigger[*solana.Log, *bindings.DecodedLog[AccessLogged]], error) {
	eventIdl, err := types.GetIdlEvent(c.IdlTypes, "AccessLogged")
	if err != nil {
		return nil, err
	}
	if len(subKeyPathAndValue) > 4 {
		return nil, fmt.Errorf("too many subkey path and value pairs: %d", len(subKeyPathAndValue))
	}
	subKeyPaths, subKeyFilters, err := bindings.ValidateSubKeyPathAndValue[AccessLogged](subKeyPathAndValue)
	if err != nil {
		return nil, fmt.Errorf("failed to validate subkey path and value: %w", err)
	}
	rawTrigger := solana.LogTrigger(chainSelector, &solana.FilterLogTriggerRequest{
		Address:       types.PublicKey(ProgramID),
		EventIdl:      eventIdl,
		EventName:     "AccessLogged",
		EventSig:      Event_AccessLogged,
		SubkeyFilters: subKeyFilters,
		SubkeyPaths:   subKeyPaths,
	})
	return &AccessLoggedTrigger{Trigger: rawTrigger}, nil
}

func ParseEvent_DataUpdated(eventData []byte) (*DataUpdated, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DataUpdated {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DataUpdated, binary.FormatDiscriminator(discriminator))
	}
	event := new(DataUpdated)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DataUpdated: %w", err)
	}
	return event, nil
}

func (c *Codec) DecodeDataUpdated(event *solana.Log) (*DataUpdated, error) {
	res, err := ParseEvent_DataUpdated(event.Data)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type DataUpdatedTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
	contract *MyProject
}

func (t *DataUpdatedTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[DataUpdated], error) {
	decoded, err := t.contract.Codec.DecodeDataUpdated(l)
	if err != nil {
		return nil, err
	}
	return &bindings.DecodedLog[DataUpdated]{
		Data: *decoded,
		Log:  l,
	}, nil
}

func (c *MyProject) LogTrigger_DataUpdated(chainSelector uint64, subKeyPathAndValue []solana.SubKeyPathAndFilter) (cre.Trigger[*solana.Log, *bindings.DecodedLog[DataUpdated]], error) {
	eventIdl, err := types.GetIdlEvent(c.IdlTypes, "DataUpdated")
	if err != nil {
		return nil, err
	}
	if len(subKeyPathAndValue) > 4 {
		return nil, fmt.Errorf("too many subkey path and value pairs: %d", len(subKeyPathAndValue))
	}
	subKeyPaths, subKeyFilters, err := bindings.ValidateSubKeyPathAndValue[DataUpdated](subKeyPathAndValue)
	if err != nil {
		return nil, fmt.Errorf("failed to validate subkey path and value: %w", err)
	}
	rawTrigger := solana.LogTrigger(chainSelector, &solana.FilterLogTriggerRequest{
		Address:       types.PublicKey(ProgramID),
		EventIdl:      eventIdl,
		EventName:     "DataUpdated",
		EventSig:      Event_DataUpdated,
		SubkeyFilters: subKeyFilters,
		SubkeyPaths:   subKeyPaths,
	})
	return &DataUpdatedTrigger{Trigger: rawTrigger}, nil
}
