// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package my_project

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	idl "github.com/gagliardetto/anchor-go/idl"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
	solana "github.com/smartcontractkit/cre-cli/cmd/generate-bindings/solana_bindings/cre-sdk-go/capabilities/blockchain/solana"
)

type MyProject struct {
	IDL    *idl.Idl
	client *solana.Client
}

type AccessLogged struct {
	Caller  solanago.PublicKey `json:"caller"`
	Message string             `json:"message"`
}

func (obj AccessLogged) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Caller`:
	err = encoder.Encode(obj.Caller)
	if err != nil {
		return errors.NewField("Caller", err)
	}
	// Serialize `Message`:
	err = encoder.Encode(obj.Message)
	if err != nil {
		return errors.NewField("Message", err)
	}
	return nil
}

func (obj AccessLogged) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessLogged: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessLogged) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Caller`:
	err = decoder.Decode(&obj.Caller)
	if err != nil {
		return errors.NewField("Caller", err)
	}
	// Deserialize `Message`:
	err = decoder.Decode(&obj.Message)
	if err != nil {
		return errors.NewField("Message", err)
	}
	return nil
}

func (obj *AccessLogged) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessLogged: %w", err)
	}
	return nil
}

func UnmarshalAccessLogged(buf []byte) (*AccessLogged, error) {
	obj := new(AccessLogged)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type DataAccount struct {
	Data string `json:"data"`
}

func (obj DataAccount) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Data`:
	err = encoder.Encode(obj.Data)
	if err != nil {
		return errors.NewField("Data", err)
	}
	return nil
}

func (obj DataAccount) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding DataAccount: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *DataAccount) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Data`:
	err = decoder.Decode(&obj.Data)
	if err != nil {
		return errors.NewField("Data", err)
	}
	return nil
}

func (obj *DataAccount) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling DataAccount: %w", err)
	}
	return nil
}

func UnmarshalDataAccount(buf []byte) (*DataAccount, error) {
	obj := new(DataAccount)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type DataUpdated struct {
	Sender solanago.PublicKey `json:"sender"`
	Value  string             `json:"value"`
}

func (obj DataUpdated) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Sender`:
	err = encoder.Encode(obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Serialize `Value`:
	err = encoder.Encode(obj.Value)
	if err != nil {
		return errors.NewField("Value", err)
	}
	return nil
}

func (obj DataUpdated) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding DataUpdated: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *DataUpdated) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Sender`:
	err = decoder.Decode(&obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Deserialize `Value`:
	err = decoder.Decode(&obj.Value)
	if err != nil {
		return errors.NewField("Value", err)
	}
	return nil
}

func (obj *DataUpdated) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling DataUpdated: %w", err)
	}
	return nil
}

func UnmarshalDataUpdated(buf []byte) (*DataUpdated, error) {
	obj := new(DataUpdated)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
