// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package my_project_modified

import (
	"fmt"
	"context"

	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
	"github.com/gagliardetto/solana-go/rpc"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_DataAccount:
		value := new(DataAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as DataAccount: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_DataAccount(accountData []byte) (*DataAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_DataAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_DataAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(DataAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type DataAccount: %w", err)
	}
	return acc, nil
}

func ReadAccount_DataAccount(seeds [][]byte, client *rpc.Client) (*DataAccount, error) {
	accountAddress, _, err := solanago.FindProgramAddress(seeds, ProgramID)
	if err != nil {
		return nil, fmt.Errorf("failed to find program address: %w", err)
	}
	resp, err := client.GetAccountInfoWithOpts(context.Background(), accountAddress, &rpc.GetAccountInfoOpts{
		Commitment: rpc.CommitmentConfirmed,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get account info: %w", err)
	}
	acc, err := ParseAccount_DataAccount(resp.Value.Data.GetBinary())
	if err != nil {
		return nil, fmt.Errorf("failed to parse account: %w", err)
	}
	return acc, nil
}


func ReadAccount_DataAccount(seeds [][]byte, runtime cre.Runtime, blockNumber *big.Int) (*DataAccount, error) {
	accountAddress, _, err := solanago.FindProgramAddress(seeds, ProgramID)

	// cre account read
	promise := cre.ThenPromise(bn, func(bn *pb.BigInt) cre.Promise[*solana.ReadAccountReply] {
		return c.client.ReadAccount(runtime, &solana.ReadAccountRequest{
			Call:        &solana.ReadAccountMsg{AccountAddress: accountAddress},
			BlockNumber: bn, // can be slot or block number or commitment type
		})
	})
	return cre.Then(promise, func(response *solana.ReadAccountReply) (*DataAccount, error) {
		return ParseAccount_DataAccount(response.Data)
	})
}

