//nolint:all // Forked from anchor-go generator, maintaining original code structure
package generator

import (
	"fmt"

	. "github.com/dave/jennifer/jen"
)

func (g *Generator) genfile_triggers() (*OutputFile, error) {
	file := NewFile(g.options.Package)
	file.HeaderComment("Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.")
	file.HeaderComment("This file contains log trigger bindings for events defined in the IDL.")

	// Blank imports to ensure types are referenced.
	file.Var().Defs(
		Id("_").Op("=").Qual(PkgSolanaCre, "FilterLogTriggerRequest").Values(),
		Id("_").Op("=").Qual(PkgBindings, "LogTriggerOptions").Values(),
		Id("_").Op("=").Qual(PkgBindings, "DecodedLog").Types(Id("struct{}")).Values(),
	)
	file.Line()

	file.Comment("Events")
	file.Comment("The <Event>Filters struct should be used as a filter for log triggers.")
	file.Comment("Only top-level scalar fields with supported subkey encodings are auto-filterable.")
	file.Comment("Nested structs, vecs, arrays, bool, u128, and i128 require manual SubkeyConfig.")
	file.Line()

	for _, event := range g.idl.Events {
		fields, err := g.getEventStructFields(event.Name)
		if err != nil {
			return nil, fmt.Errorf("event %s: %w", event.Name, err)
		}

		filterFields := getEventFilterFields(fields)

		file.Add(creEventFiltersStruct(event.Name, filterFields))
		file.Line()
		file.Add(creEncodeSubkeysForEvent(event.Name, filterFields))
		file.Line()
		file.Add(creLogTriggerForEvent(event.Name, g))
		file.Line()
	}

	return &OutputFile{
		Name: "triggers.go",
		File: file,
	}, nil
}
