server {
    listen 80;
    server_name localhost;
    charset utf-8;

    # Must match cre AuthRedirectURI: http://localhost:53682/callback
    location = /callback {
        default_type text/html;
        alias /usr/share/nginx/html/callback/index.html;
    }
}
