// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package solanamock

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"google.golang.org/protobuf/types/known/anypb"


	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre/testutils/registry"
	solana "github.com/smartcontractkit/cre-cli/cmd/generate-bindings/solana_bindings/cre-sdk-go/capabilities/blockchain/solana"
)

// avoid unused imports
var _ = registry.Registry{}

func NewClientCapability(ChainSelector uint64, t testing.TB) (*ClientCapability, error) {
	c := &ClientCapability{
		ChainSelector: ChainSelector,
	}
	reg := registry.GetRegistry(t)
	err := reg.RegisterCapability(c)
	return c, err
}

type ClientCapability struct {
	ChainSelector uint64
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetAccountInfoWithOpts func(ctx context.Context, input *solana.GetAccountInfoRequest) (*solana.GetAccountInfoReply, error)
	WriteReport func(ctx context.Context, input *solana.WriteCreReportRequest) (*solana.WriteReportReply, error)
}

func (c *ClientCapability) Invoke(ctx context.Context, request *sdkpb.CapabilityRequest) *sdkpb.CapabilityResponse {
	capResp := &sdkpb.CapabilityResponse{}
	switch request.Method {
	case "GetAccountInfoWithOpts":
		input := &solana.GetAccountInfoRequest{}
		resp, _ := c.GetAccountInfoWithOpts(ctx, input)
		payload, _ := anypb.New(resp)
		capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
	case "WriteReport":
		input := &solana.WriteCreReportRequest{}
		if c.WriteReport == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for WriteReport"}
			break
		}
		resp, _ := c.WriteReport(ctx, input)
		payload, _ := anypb.New(resp)
		capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
	default:
		capResp.Response = &sdkpb.CapabilityResponse_Error{Error: fmt.Sprintf("method %s not found", request.Method)}
	}

	return capResp
}

func (c *ClientCapability) ID() string {
	return "solana" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0"
}
