ENVIRONMENTS:
  SANDBOX:
    CRE_CLI_UI_URL: https://cre-ui.main.sand.cldev.sh
    CRE_CLI_COGNITO_URL: https://cre-main-sandbox.auth.us-west-2.amazoncognito.com
    CRE_CLI_CLIENT_ID: 5l525desfnumtlnh7bdnpomahn
    CRE_CLI_GRAPHQL_URL: https://cre-platform-graphql.main.sand.cldev.sh/graphql
    CRE_CLI_USER_POOL_ID: us-west-2_EGfnXKUQR
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway.main.sand.cldev.sh

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0x51D3acf4526e014deBf9884159A57f63Fc0Ca49D"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_SELECTOR: 10344971235874465080 # base-sepolia
    CRE_CLI_CAPABILITIES_REGISTRY_ADDRESS: "0x02471a03A86ac92DE793af303E9f756f0aE60677"
    CRE_CLI_CAPABILITIES_REGISTRY_CHAIN_SELECTOR: 16015286601757825753 # eth-sepolia


  STAGING:
    CRE_CLI_UI_URL: https://cre-ui.main.stage.cldev.sh
    CRE_CLI_COGNITO_URL: https://cre-main-staging.auth.us-west-2.amazoncognito.com
    CRE_CLI_CLIENT_ID: "2g6tfii1ekglrcib5nqi79l2p1"
    CRE_CLI_GRAPHQL_URL: https://cre-platform-graphql.main.stage.cldev.sh/graphql
    CRE_CLI_USER_POOL_ID: "us-west-2_WuxfEGZDQ"
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway.main.sand.cldev.sh

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0xcF4629d8DC7a5fa17F4D77233F5b953225669821"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_SELECTOR: 10344971235874465080 # base-sepolia
    CRE_CLI_CAPABILITIES_REGISTRY_ADDRESS: "0x3392AC757B05bCb0DCEcBE298674462Dd30DEd29"
    CRE_CLI_CAPABILITIES_REGISTRY_CHAIN_SELECTOR: 10344971235874465080 # base-sepolia

    CRE_GATEWAY_URL: https://cre-gateway.main.sand.cldev.sh

  PRODUCTION:
    CRE_CLI_UI_URL: ""
    CRE_CLI_COGNITO_URL: ""
    CRE_CLI_CLIENT_ID: ""
    CRE_CLI_GRAPHQL_URL: ""
    CRE_CLI_USER_POOL_ID: ""
    CRE_VAULT_DON_GATEWAY_URL: ""

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: ""
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_SELECTOR: 0
    CRE_CLI_CAPABILITIES_REGISTRY_ADDRESS: ""
    CRE_CLI_CAPABILITIES_REGISTRY_CHAIN_SELECTOR: 0
