ENVIRONMENTS:
  SANDBOX:
    CRE_CLI_UI_URL: https://cre-ui.main.sand.cldev.sh
    CRE_CLI_AUTH_BASE: https://cre-sandbox.us.auth0.com
    CRE_CLI_CLIENT_ID: KERrSYowuRhVyXUrI3u7pI8nnY95bIGt
    CRE_CLI_AUDIENCE: https://graphql.cre.dev.internal.cldev.sh/
    CRE_CLI_GRAPHQL_URL: https://graphql.cre.dev.internal.cldev.sh/graphql
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway.main.sand.cldev.sh

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0xBc9Eb5D8358c9dF4E74fF149E15891F88f0203a6"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia-base-1" # base-sepolia

    CRE_CLI_CAPABILITIES_REGISTRY_ADDRESS: "0x02471a03A86ac92DE793af303E9f756f0aE60677"
    CRE_CLI_CAPABILITIES_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia" # eth-sepolia

  STAGING:
    CRE_CLI_UI_URL: https://cre-ui.main.stage.cldev.sh
    CRE_CLI_AUTH_BASE: https://cre-staging.us.auth0.com
    CRE_CLI_CLIENT_ID: pKF1lgw56KKUo5LCl8kEREtVY50YB2Gd
    CRE_CLI_AUDIENCE: https://graphql.cre.stage.internal.cldev.sh/
    CRE_CLI_GRAPHQL_URL: https://graphql.cre.stage.internal.cldev.sh/graphql
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway.main.stage.cldev.sh

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0xcF4629d8DC7a5fa17F4D77233F5b953225669821"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia-base-1" # base-sepolia

    CRE_CLI_CAPABILITIES_REGISTRY_ADDRESS: "0x3392AC757B05bCb0DCEcBE298674462Dd30DEd29"
    CRE_CLI_CAPABILITIES_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia-base-1" # base-sepolia
