ENVIRONMENTS:
  SANDBOX:
    CRE_CLI_AUTH_BASE: https://cre-sandbox.us.auth0.com
    CRE_CLI_CLIENT_ID: KERrSYowuRhVyXUrI3u7pI8nnY95bIGt
    CRE_CLI_AUDIENCE: https://graphql.cre.dev.internal.cldev.sh/
    CRE_CLI_GRAPHQL_URL: https://graphql-cre-dev.tailf8f749.ts.net/graphql
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway.main.sand.cldev.sh

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0xBc9Eb5D8358c9dF4E74fF149E15891F88f0203a6"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia-base-1" # base-sepolia
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_EXPLORER_URL: "https://sepolia.basescan.org"

    CRE_CLI_CAPABILITIES_REGISTRY_ADDRESS: "0x02471a03A86ac92DE793af303E9f756f0aE60677"
    CRE_CLI_CAPABILITIES_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia" # eth-sepolia

  STAGING:
    CRE_CLI_AUTH_BASE: https://cre-staging.us.auth0.com
    CRE_CLI_CLIENT_ID: pKF1lgw56KKUo5LCl8kEREtVY50YB2Gd
    CRE_CLI_AUDIENCE: https://graphql.cre.stage.internal.cldev.sh/
    CRE_CLI_GRAPHQL_URL: https://graphql-cre-stage.tailf8f749.ts.net/graphql
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway-one-zone-a.main.stage.cldev.sh/


    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0x7e69E853D9Ce50C2562a69823c80E01360019Cef"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia-base-1" # base-sepolia
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_EXPLORER_URL: "https://sepolia.basescan.org"

    CRE_CLI_CAPABILITIES_REGISTRY_ADDRESS: "0x3392AC757B05bCb0DCEcBE298674462Dd30DEd29"
    CRE_CLI_CAPABILITIES_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia-base-1" # base-sepolia
