ENVIRONMENTS:
  SANDBOX:
    CRE_CLI_AUTH_BASE: https://login-dev.cre.cldev.cloud
    CRE_CLI_CLIENT_ID: KERrSYowuRhVyXUrI3u7pI8nnY95bIGt
    CRE_CLI_AUDIENCE: https://graphql.cre.dev.internal.cldev.sh/
    CRE_CLI_GRAPHQL_URL: https://graphql-cre-dev.tailf8f749.ts.net/graphql
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway-one-zone-a.main.stage.cldev.sh/

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0x7e69E853D9Ce50C2562a69823c80E01360019Cef"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia" # eth-sepolia
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_EXPLORER_URL: "https://sepolia.etherscan.io"

  STAGING:
    CRE_CLI_AUTH_BASE: https://login-stage.cre.cldev.cloud
    CRE_CLI_CLIENT_ID: pKF1lgw56KKUo5LCl8kEREtVY50YB2Gd
    CRE_CLI_AUDIENCE: https://graphql.cre.stage.internal.cldev.sh/
    CRE_CLI_GRAPHQL_URL: https://graphql-cre-stage.tailf8f749.ts.net/graphql
    CRE_VAULT_DON_GATEWAY_URL: https://cre-gateway-one-zone-a.main.stage.cldev.sh/

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0xaE55eB3EDAc48a1163EE2cbb1205bE1e90Ea1135"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_NAME: "ethereum-testnet-sepolia" # eth-sepolia
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_EXPLORER_URL: "https://sepolia.etherscan.io"

  PRODUCTION:
    CRE_CLI_AUTH_BASE: https://login.chain.link
    CRE_CLI_CLIENT_ID: vMqPqJ3ApbeN8jNeA42Dn4UxbkfhQQkW
    CRE_CLI_AUDIENCE: https://api.cre.chain.link
    CRE_CLI_GRAPHQL_URL: https://api.cre.chain.link/graphql
    CRE_VAULT_DON_GATEWAY_URL: https://01.gateway.zone-a.cre.chain.link

    CRE_CLI_WORKFLOW_REGISTRY_ADDRESS: "0x4ac54353fa4fa961afcc5ec4b118596d3305e7e5"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_NAME: "ethereum-mainnet"
    CRE_CLI_WORKFLOW_REGISTRY_CHAIN_EXPLORER_URL: "https://etherscan.io"
