// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cre-sdk-go/capabilities/blockchain/solana/protos/get_account_info_reply_test.proto

// protoc --go_out=. --go_opt=paths=source_relative cre-sdk-go/capabilities/blockchain/solana/protos/get_account_info_reply_test.proto

package solana

import (
	// protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	// protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	// reflect "reflect"
	// sync "sync"
	// unsafe "unsafe"
)

// const (
// 	// Verify that this generated code is sufficiently up-to-date.
// 	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
// 	// Verify that runtime/protoimpl is sufficiently up-to-date.
// 	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
// )

// type EncodingType int32

// const (
// 	EncodingType_ENCODING_TYPE_UNSPECIFIED EncodingType = 0
// 	EncodingType_ENCODING_TYPE_BASE58      EncodingType = 1
// 	EncodingType_ENCODING_TYPE_BASE64      EncodingType = 2
// 	EncodingType_ENCODING_TYPE_JSON        EncodingType = 3
// )

// // Enum value maps for EncodingType.
// var (
// 	EncodingType_name = map[int32]string{
// 		0: "ENCODING_TYPE_UNSPECIFIED",
// 		1: "ENCODING_TYPE_BASE58",
// 		2: "ENCODING_TYPE_BASE64",
// 		3: "ENCODING_TYPE_JSON",
// 	}
// 	EncodingType_value = map[string]int32{
// 		"ENCODING_TYPE_UNSPECIFIED": 0,
// 		"ENCODING_TYPE_BASE58":      1,
// 		"ENCODING_TYPE_BASE64":      2,
// 		"ENCODING_TYPE_JSON":        3,
// 	}
// )

// func (x EncodingType) Enum() *EncodingType {
// 	p := new(EncodingType)
// 	*p = x
// 	return p
// }

// func (x EncodingType) String() string {
// 	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
// }

// func (EncodingType) Descriptor() protoreflect.EnumDescriptor {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_enumTypes[0].Descriptor()
// }

// func (EncodingType) Type() protoreflect.EnumType {
// 	return &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_enumTypes[0]
// }

// func (x EncodingType) Number() protoreflect.EnumNumber {
// 	return protoreflect.EnumNumber(x)
// }

// // Deprecated: Use EncodingType.Descriptor instead.
// func (EncodingType) EnumDescriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{0}
// }

// type TxStatus int32

// const (
// 	TxStatus_TX_STATUS_FATAL    TxStatus = 0
// 	TxStatus_TX_STATUS_REVERTED TxStatus = 1
// 	TxStatus_TX_STATUS_SUCCESS  TxStatus = 2
// )

// // Enum value maps for TxStatus.
// var (
// 	TxStatus_name = map[int32]string{
// 		0: "TX_STATUS_FATAL",
// 		1: "TX_STATUS_REVERTED",
// 		2: "TX_STATUS_SUCCESS",
// 	}
// 	TxStatus_value = map[string]int32{
// 		"TX_STATUS_FATAL":    0,
// 		"TX_STATUS_REVERTED": 1,
// 		"TX_STATUS_SUCCESS":  2,
// 	}
// )

// func (x TxStatus) Enum() *TxStatus {
// 	p := new(TxStatus)
// 	*p = x
// 	return p
// }

// func (x TxStatus) String() string {
// 	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
// }

// func (TxStatus) Descriptor() protoreflect.EnumDescriptor {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_enumTypes[1].Descriptor()
// }

// func (TxStatus) Type() protoreflect.EnumType {
// 	return &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_enumTypes[1]
// }

// func (x TxStatus) Number() protoreflect.EnumNumber {
// 	return protoreflect.EnumNumber(x)
// }

// // Deprecated: Use TxStatus.Descriptor instead.
// func (TxStatus) EnumDescriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{1}
// }

// type Context struct {
// 	state         protoimpl.MessageState `protogen:"open.v1"`
// 	unknownFields protoimpl.UnknownFields
// 	sizeCache     protoimpl.SizeCache
// }

// func (x *Context) Reset() {
// 	*x = Context{}
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[0]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *Context) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*Context) ProtoMessage() {}

// func (x *Context) ProtoReflect() protoreflect.Message {
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[0]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use Context.ProtoReflect.Descriptor instead.
// func (*Context) Descriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{0}
// }

// type RPCContext struct {
// 	state         protoimpl.MessageState `protogen:"open.v1"`
// 	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
// 	unknownFields protoimpl.UnknownFields
// 	sizeCache     protoimpl.SizeCache
// }

// func (x *RPCContext) Reset() {
// 	*x = RPCContext{}
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[1]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *RPCContext) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*RPCContext) ProtoMessage() {}

// func (x *RPCContext) ProtoReflect() protoreflect.Message {
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[1]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use RPCContext.ProtoReflect.Descriptor instead.
// func (*RPCContext) Descriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{1}
// }

// func (x *RPCContext) GetContext() *Context {
// 	if x != nil {
// 		return x.Context
// 	}
// 	return nil
// }

// type DataBytesOrJSON struct {
// 	state           protoimpl.MessageState `protogen:"open.v1"`
// 	RawDataEncoding EncodingType           `protobuf:"varint,1,opt,name=raw_data_encoding,json=rawDataEncoding,proto3,enum=sdkpb.EncodingType" json:"raw_data_encoding,omitempty"`
// 	AsDecodedBinary []byte                 `protobuf:"bytes,2,opt,name=as_decoded_binary,json=asDecodedBinary,proto3" json:"as_decoded_binary,omitempty"`
// 	AsJson          []byte                 `protobuf:"bytes,3,opt,name=as_json,json=asJson,proto3" json:"as_json,omitempty"`
// 	unknownFields   protoimpl.UnknownFields
// 	sizeCache       protoimpl.SizeCache
// }

// func (x *DataBytesOrJSON) Reset() {
// 	*x = DataBytesOrJSON{}
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[2]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *DataBytesOrJSON) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*DataBytesOrJSON) ProtoMessage() {}

// func (x *DataBytesOrJSON) ProtoReflect() protoreflect.Message {
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[2]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use DataBytesOrJSON.ProtoReflect.Descriptor instead.
// func (*DataBytesOrJSON) Descriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{2}
// }

// func (x *DataBytesOrJSON) GetRawDataEncoding() EncodingType {
// 	if x != nil {
// 		return x.RawDataEncoding
// 	}
// 	return EncodingType_ENCODING_TYPE_UNSPECIFIED
// }

// func (x *DataBytesOrJSON) GetAsDecodedBinary() []byte {
// 	if x != nil {
// 		return x.AsDecodedBinary
// 	}
// 	return nil
// }

// func (x *DataBytesOrJSON) GetAsJson() []byte {
// 	if x != nil {
// 		return x.AsJson
// 	}
// 	return nil
// }

// type Account struct {
// 	state         protoimpl.MessageState `protogen:"open.v1"`
// 	Lamports      uint64                 `protobuf:"varint,1,opt,name=lamports,proto3" json:"lamports,omitempty"`
// 	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"` // was PublicKey
// 	Data          *DataBytesOrJSON       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
// 	Executable    bool                   `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
// 	RentEpoch     string                 `protobuf:"bytes,5,opt,name=rent_epoch,json=rentEpoch,proto3" json:"rent_epoch,omitempty"` // represents *big.Int as string
// 	Space         uint64                 `protobuf:"varint,6,opt,name=space,proto3" json:"space,omitempty"`
// 	unknownFields protoimpl.UnknownFields
// 	sizeCache     protoimpl.SizeCache
// }

// func (x *Account) Reset() {
// 	*x = Account{}
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[3]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *Account) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*Account) ProtoMessage() {}

// func (x *Account) ProtoReflect() protoreflect.Message {
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[3]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use Account.ProtoReflect.Descriptor instead.
// func (*Account) Descriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{3}
// }

// func (x *Account) GetLamports() uint64 {
// 	if x != nil {
// 		return x.Lamports
// 	}
// 	return 0
// }

// func (x *Account) GetOwner() string {
// 	if x != nil {
// 		return x.Owner
// 	}
// 	return ""
// }

// func (x *Account) GetData() *DataBytesOrJSON {
// 	if x != nil {
// 		return x.Data
// 	}
// 	return nil
// }

// func (x *Account) GetExecutable() bool {
// 	if x != nil {
// 		return x.Executable
// 	}
// 	return false
// }

// func (x *Account) GetRentEpoch() string {
// 	if x != nil {
// 		return x.RentEpoch
// 	}
// 	return ""
// }

// func (x *Account) GetSpace() uint64 {
// 	if x != nil {
// 		return x.Space
// 	}
// 	return 0
// }

// type GetAccountInfoReply struct {
// 	state         protoimpl.MessageState `protogen:"open.v1"`
// 	RpcContext    *RPCContext            `protobuf:"bytes,1,opt,name=rpc_context,json=rpcContext,proto3" json:"rpc_context,omitempty"`
// 	Value         *Account               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
// 	unknownFields protoimpl.UnknownFields
// 	sizeCache     protoimpl.SizeCache
// }

// func (x *GetAccountInfoReply) Reset() {
// 	*x = GetAccountInfoReply{}
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[4]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *GetAccountInfoReply) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*GetAccountInfoReply) ProtoMessage() {}

// func (x *GetAccountInfoReply) ProtoReflect() protoreflect.Message {
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[4]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use GetAccountInfoReply.ProtoReflect.Descriptor instead.
// func (*GetAccountInfoReply) Descriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{4}
// }

// func (x *GetAccountInfoReply) GetRpcContext() *RPCContext {
// 	if x != nil {
// 		return x.RpcContext
// 	}
// 	return nil
// }

// func (x *GetAccountInfoReply) GetValue() *Account {
// 	if x != nil {
// 		return x.Value
// 	}
// 	return nil
// }

// type ReceiverContractExecutionStatus struct {
// 	state protoimpl.MessageState `protogen:"open.v1"`
// 	// Placeholder – fill in actual fields later
// 	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
// 	Code          int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
// 	unknownFields protoimpl.UnknownFields
// 	sizeCache     protoimpl.SizeCache
// }

// func (x *ReceiverContractExecutionStatus) Reset() {
// 	*x = ReceiverContractExecutionStatus{}
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[5]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *ReceiverContractExecutionStatus) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*ReceiverContractExecutionStatus) ProtoMessage() {}

// func (x *ReceiverContractExecutionStatus) ProtoReflect() protoreflect.Message {
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[5]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use ReceiverContractExecutionStatus.ProtoReflect.Descriptor instead.
// func (*ReceiverContractExecutionStatus) Descriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{5}
// }

// func (x *ReceiverContractExecutionStatus) GetMessage() string {
// 	if x != nil {
// 		return x.Message
// 	}
// 	return ""
// }

// func (x *ReceiverContractExecutionStatus) GetCode() int32 {
// 	if x != nil {
// 		return x.Code
// 	}
// 	return 0
// }

// type WriteReportReply struct {
// 	state                   protoimpl.MessageState           `protogen:"open.v1"`
// 	TxStatus                TxStatus                         `protobuf:"varint,1,opt,name=tx_status,json=txStatus,proto3,enum=sdkpb.TxStatus" json:"tx_status,omitempty"`
// 	ReceiverExecutionStatus *ReceiverContractExecutionStatus `protobuf:"bytes,2,opt,name=receiver_execution_status,json=receiverExecutionStatus,proto3" json:"receiver_execution_status,omitempty"`
// 	TxHash                  []byte                           `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
// 	ErrorMessage            string                           `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
// 	unknownFields           protoimpl.UnknownFields
// 	sizeCache               protoimpl.SizeCache
// }

// func (x *WriteReportReply) Reset() {
// 	*x = WriteReportReply{}
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[6]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *WriteReportReply) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*WriteReportReply) ProtoMessage() {}

// func (x *WriteReportReply) ProtoReflect() protoreflect.Message {
// 	mi := &file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes[6]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use WriteReportReply.ProtoReflect.Descriptor instead.
// func (*WriteReportReply) Descriptor() ([]byte, []int) {
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP(), []int{6}
// }

// func (x *WriteReportReply) GetTxStatus() TxStatus {
// 	if x != nil {
// 		return x.TxStatus
// 	}
// 	return TxStatus_TX_STATUS_FATAL
// }

// func (x *WriteReportReply) GetReceiverExecutionStatus() *ReceiverContractExecutionStatus {
// 	if x != nil {
// 		return x.ReceiverExecutionStatus
// 	}
// 	return nil
// }

// func (x *WriteReportReply) GetTxHash() []byte {
// 	if x != nil {
// 		return x.TxHash
// 	}
// 	return nil
// }

// func (x *WriteReportReply) GetErrorMessage() string {
// 	if x != nil {
// 		return x.ErrorMessage
// 	}
// 	return ""
// }

// var File_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto protoreflect.FileDescriptor

// const file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDesc = "" +
// 	"\n" +
// 	"Rcre-sdk-go/capabilities/blockchain/solana/protos/get_account_info_reply_test.proto\x12\x05sdkpb\"\t\n" +
// 	"\aContext\"6\n" +
// 	"\n" +
// 	"RPCContext\x12(\n" +
// 	"\acontext\x18\x01 \x01(\v2\x0e.sdkpb.ContextR\acontext\"\x97\x01\n" +
// 	"\x0fDataBytesOrJSON\x12?\n" +
// 	"\x11raw_data_encoding\x18\x01 \x01(\x0e2\x13.sdkpb.EncodingTypeR\x0frawDataEncoding\x12*\n" +
// 	"\x11as_decoded_binary\x18\x02 \x01(\fR\x0fasDecodedBinary\x12\x17\n" +
// 	"\aas_json\x18\x03 \x01(\fR\x06asJson\"\xbc\x01\n" +
// 	"\aAccount\x12\x1a\n" +
// 	"\blamports\x18\x01 \x01(\x04R\blamports\x12\x14\n" +
// 	"\x05owner\x18\x02 \x01(\tR\x05owner\x12*\n" +
// 	"\x04data\x18\x03 \x01(\v2\x16.sdkpb.DataBytesOrJSONR\x04data\x12\x1e\n" +
// 	"\n" +
// 	"executable\x18\x04 \x01(\bR\n" +
// 	"executable\x12\x1d\n" +
// 	"\n" +
// 	"rent_epoch\x18\x05 \x01(\tR\trentEpoch\x12\x14\n" +
// 	"\x05space\x18\x06 \x01(\x04R\x05space\"o\n" +
// 	"\x13GetAccountInfoReply\x122\n" +
// 	"\vrpc_context\x18\x01 \x01(\v2\x11.sdkpb.RPCContextR\n" +
// 	"rpcContext\x12$\n" +
// 	"\x05value\x18\x02 \x01(\v2\x0e.sdkpb.AccountR\x05value\"O\n" +
// 	"\x1fReceiverContractExecutionStatus\x12\x18\n" +
// 	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
// 	"\x04code\x18\x02 \x01(\x05R\x04code\"\xe2\x01\n" +
// 	"\x10WriteReportReply\x12,\n" +
// 	"\ttx_status\x18\x01 \x01(\x0e2\x0f.sdkpb.TxStatusR\btxStatus\x12b\n" +
// 	"\x19receiver_execution_status\x18\x02 \x01(\v2&.sdkpb.ReceiverContractExecutionStatusR\x17receiverExecutionStatus\x12\x17\n" +
// 	"\atx_hash\x18\x03 \x01(\fR\x06txHash\x12#\n" +
// 	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*y\n" +
// 	"\fEncodingType\x12\x1d\n" +
// 	"\x19ENCODING_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
// 	"\x14ENCODING_TYPE_BASE58\x10\x01\x12\x18\n" +
// 	"\x14ENCODING_TYPE_BASE64\x10\x02\x12\x16\n" +
// 	"\x12ENCODING_TYPE_JSON\x10\x03*N\n" +
// 	"\bTxStatus\x12\x13\n" +
// 	"\x0fTX_STATUS_FATAL\x10\x00\x12\x16\n" +
// 	"\x12TX_STATUS_REVERTED\x10\x01\x12\x15\n" +
// 	"\x11TX_STATUS_SUCCESS\x10\x02B\x1eZ\x1cyour/module/path/sdkpb;sdkpbb\x06proto3"

// var (
// 	file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescOnce sync.Once
// 	file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescData []byte
// )

// func file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescGZIP() []byte {
// 	file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescOnce.Do(func() {
// 		file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDesc), len(file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDesc)))
// 	})
// 	return file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDescData
// }

// var file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
// var file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
// var file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_goTypes = []any{
// 	(EncodingType)(0),                       // 0: sdkpb.EncodingType
// 	(TxStatus)(0),                           // 1: sdkpb.TxStatus
// 	(*Context)(nil),                         // 2: sdkpb.Context
// 	(*RPCContext)(nil),                      // 3: sdkpb.RPCContext
// 	(*DataBytesOrJSON)(nil),                 // 4: sdkpb.DataBytesOrJSON
// 	(*Account)(nil),                         // 5: sdkpb.Account
// 	(*GetAccountInfoReply)(nil),             // 6: sdkpb.GetAccountInfoReply
// 	(*ReceiverContractExecutionStatus)(nil), // 7: sdkpb.ReceiverContractExecutionStatus
// 	(*WriteReportReply)(nil),                // 8: sdkpb.WriteReportReply
// }
// var file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_depIdxs = []int32{
// 	2, // 0: sdkpb.RPCContext.context:type_name -> sdkpb.Context
// 	0, // 1: sdkpb.DataBytesOrJSON.raw_data_encoding:type_name -> sdkpb.EncodingType
// 	4, // 2: sdkpb.Account.data:type_name -> sdkpb.DataBytesOrJSON
// 	3, // 3: sdkpb.GetAccountInfoReply.rpc_context:type_name -> sdkpb.RPCContext
// 	5, // 4: sdkpb.GetAccountInfoReply.value:type_name -> sdkpb.Account
// 	1, // 5: sdkpb.WriteReportReply.tx_status:type_name -> sdkpb.TxStatus
// 	7, // 6: sdkpb.WriteReportReply.receiver_execution_status:type_name -> sdkpb.ReceiverContractExecutionStatus
// 	7, // [7:7] is the sub-list for method output_type
// 	7, // [7:7] is the sub-list for method input_type
// 	7, // [7:7] is the sub-list for extension type_name
// 	7, // [7:7] is the sub-list for extension extendee
// 	0, // [0:7] is the sub-list for field type_name
// }

// func init() {
// 	file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_init()
// }
// func file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_init() {
// 	if File_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto != nil {
// 		return
// 	}
// 	type x struct{}
// 	out := protoimpl.TypeBuilder{
// 		File: protoimpl.DescBuilder{
// 			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
// 			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDesc), len(file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_rawDesc)),
// 			NumEnums:      2,
// 			NumMessages:   7,
// 			NumExtensions: 0,
// 			NumServices:   0,
// 		},
// 		GoTypes:           file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_goTypes,
// 		DependencyIndexes: file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_depIdxs,
// 		EnumInfos:         file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_enumTypes,
// 		MessageInfos:      file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_msgTypes,
// 	}.Build()
// 	File_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto = out.File
// 	file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_goTypes = nil
// 	file_cre_sdk_go_capabilities_blockchain_solana_protos_get_account_info_reply_test_proto_depIdxs = nil
// }
