// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package data_storage

import binary "github.com/gagliardetto/binary"

// Account discriminators
var (
	Account_DataAccount = binary.TypeID{85, 240, 182, 158, 76, 7, 18, 233}
)

// Event discriminators
var (
	Event_AccessLogged = binary.TypeID{243, 53, 225, 71, 64, 120, 109, 25}
	Event_DynamicEvent = binary.TypeID{236, 145, 224, 161, 9, 222, 218, 237}
	Event_NoFields     = binary.TypeID{160, 156, 94, 85, 77, 122, 98, 240}
)

// Instruction discriminators
var (
	Instruction_GetMultipleReserves   = binary.TypeID{104, 122, 140, 104, 175, 151, 70, 42}
	Instruction_GetReserves           = binary.TypeID{121, 140, 237, 84, 218, 105, 48, 17}
	Instruction_GetTupleReserves      = binary.TypeID{189, 83, 186, 20, 127, 80, 109, 49}
	Instruction_InitializeDataAccount = binary.TypeID{9, 64, 78, 49, 71, 193, 15, 250}
	Instruction_LogAccess             = binary.TypeID{196, 55, 194, 24, 5, 224, 161, 204}
	Instruction_OnReport              = binary.TypeID{214, 173, 18, 221, 173, 148, 151, 208}
	Instruction_UpdateKeyValueData    = binary.TypeID{67, 137, 144, 35, 210, 126, 254, 79}
	Instruction_UpdateUserData        = binary.TypeID{11, 13, 114, 150, 194, 224, 192, 78}
)
