// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package data_storage

// Account discriminators
var (
	Account_DataAccount = [8]byte{85, 240, 182, 158, 76, 7, 18, 233}
)

// Event discriminators
var (
	Event_AccessLogged = [8]byte{243, 53, 225, 71, 64, 120, 109, 25}
	Event_DynamicEvent = [8]byte{236, 145, 224, 161, 9, 222, 218, 237}
	Event_NoFields     = [8]byte{160, 156, 94, 85, 77, 122, 98, 240}
)

// Instruction discriminators
var (
	Instruction_GetMultipleReserves   = [8]byte{104, 122, 140, 104, 175, 151, 70, 42}
	Instruction_GetReserves           = [8]byte{121, 140, 237, 84, 218, 105, 48, 17}
	Instruction_GetTupleReserves      = [8]byte{189, 83, 186, 20, 127, 80, 109, 49}
	Instruction_InitializeDataAccount = [8]byte{9, 64, 78, 49, 71, 193, 15, 250}
	Instruction_LogAccess             = [8]byte{196, 55, 194, 24, 5, 224, 161, 204}
	Instruction_OnReport              = [8]byte{214, 173, 18, 221, 173, 148, 151, 208}
	Instruction_UpdateKeyValueData    = [8]byte{67, 137, 144, 35, 210, 126, 254, 79}
	Instruction_UpdateUserData        = [8]byte{11, 13, 114, 150, 194, 224, 192, 78}
)
