// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains log trigger bindings for events defined in the IDL.

package data_storage

import (
	"fmt"

	solanago "github.com/gagliardetto/solana-go"
	solana "github.com/smartcontractkit/cre-sdk-go/capabilities/blockchain/solana"
	bindings "github.com/smartcontractkit/cre-sdk-go/capabilities/blockchain/solana/bindings"
	cre "github.com/smartcontractkit/cre-sdk-go/cre"
)

var (
	_ = solana.FilterLogTriggerRequest{}
	_ = bindings.LogTriggerOptions{}
	_ = bindings.DecodedLog[struct{}]{}
)

// Events
// The <Event>Filters struct should be used as a filter for log triggers.
// Only top-level scalar fields are filterable. Nested structs, vecs, and arrays require manual SubkeyConfig.

// AccessLoggedFilters holds optional filter values for AccessLogged log triggers.
// Set a field to filter on that value (OR across filter rows). Leave nil for wildcard.
type AccessLoggedFilters struct {
	Caller  *solanago.PublicKey
	Message *string
}

func (c *Codec) EncodeAccessLoggedSubkeys(filters []AccessLoggedFilters) ([]*solana.SubkeyConfig, error) {
	callerComparers := make([]*solana.ValueComparator, 0)
	messageComparers := make([]*solana.ValueComparator, 0)

	for _, f := range filters {
		if f.Caller != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Caller)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Caller: %w", err)
			}
			callerComparers = append(callerComparers, &solana.ValueComparator{
				Value:    val,
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
			})
		}
		if f.Message != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Message)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Message: %w", err)
			}
			messageComparers = append(messageComparers, &solana.ValueComparator{
				Value:    val,
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
			})
		}
	}

	subkeys := make([]*solana.SubkeyConfig, 0)
	if len(callerComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Path:      []string{"Caller"},
			Comparers: callerComparers,
		})
	}
	if len(messageComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Path:      []string{"Message"},
			Comparers: messageComparers,
		})
	}
	return subkeys, nil
}

// AccessLoggedTrigger wraps the raw log trigger and provides decoded AccessLogged data.
type AccessLoggedTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
	contract *DataStorage
}

// Adapt decodes the log into AccessLogged event data.
func (t *AccessLoggedTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[AccessLogged], error) {
	decoded, err := ParseEvent_AccessLogged(l.GetData())
	if err != nil {
		return nil, fmt.Errorf("failed to decode AccessLogged log: %w", err)
	}
	return &bindings.DecodedLog[AccessLogged]{
		Log:  l,
		Data: *decoded,
	}, nil
}

// LogTriggerAccessLoggedLog registers a typed log trigger for AccessLogged events.
func (c *DataStorage) LogTriggerAccessLoggedLog(
	chainSelector uint64,
	filterName string,
	filters []AccessLoggedFilters,
	opts *bindings.LogTriggerOptions,
) (cre.Trigger[*solana.Log, *bindings.DecodedLog[AccessLogged]], error) {
	subkeys, err := c.Codec.EncodeAccessLoggedSubkeys(filters)
	if err != nil {
		return nil, fmt.Errorf("failed to encode subkeys for AccessLogged: %w", err)
	}

	req := &solana.FilterLogTriggerRequest{
		Name:            filterName,
		Address:         ProgramID.Bytes(),
		EventName:       "AccessLogged",
		ContractIdlJson: []byte(IDL),
		Subkeys:         subkeys,
	}
	if opts != nil && opts.CpiFilterConfig != nil {
		req.CpiFilterConfig = opts.CpiFilterConfig
	}

	rawTrigger := solana.LogTrigger(chainSelector, req)
	return &AccessLoggedTrigger{
		Trigger:  rawTrigger,
		contract: c,
	}, nil
}

// DynamicEventFilters holds optional filter values for DynamicEvent log triggers.
// Set a field to filter on that value (OR across filter rows). Leave nil for wildcard.
type DynamicEventFilters struct {
	Key      *string
	Sender   *string
	Metadata *[]byte
}

func (c *Codec) EncodeDynamicEventSubkeys(filters []DynamicEventFilters) ([]*solana.SubkeyConfig, error) {
	keyComparers := make([]*solana.ValueComparator, 0)
	senderComparers := make([]*solana.ValueComparator, 0)
	metadataComparers := make([]*solana.ValueComparator, 0)

	for _, f := range filters {
		if f.Key != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Key)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Key: %w", err)
			}
			keyComparers = append(keyComparers, &solana.ValueComparator{
				Value:    val,
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
			})
		}
		if f.Sender != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Sender)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Sender: %w", err)
			}
			senderComparers = append(senderComparers, &solana.ValueComparator{
				Value:    val,
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
			})
		}
		if f.Metadata != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Metadata)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Metadata: %w", err)
			}
			metadataComparers = append(metadataComparers, &solana.ValueComparator{
				Value:    val,
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
			})
		}
	}

	subkeys := make([]*solana.SubkeyConfig, 0)
	if len(keyComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Path:      []string{"Key"},
			Comparers: keyComparers,
		})
	}
	if len(senderComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Path:      []string{"Sender"},
			Comparers: senderComparers,
		})
	}
	if len(metadataComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Path:      []string{"Metadata"},
			Comparers: metadataComparers,
		})
	}
	return subkeys, nil
}

// DynamicEventTrigger wraps the raw log trigger and provides decoded DynamicEvent data.
type DynamicEventTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
	contract *DataStorage
}

func (t *DynamicEventTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[DynamicEvent], error) {
	decoded, err := ParseEvent_DynamicEvent(l.GetData())
	if err != nil {
		return nil, fmt.Errorf("failed to decode DynamicEvent log: %w", err)
	}
	return &bindings.DecodedLog[DynamicEvent]{
		Log:  l,
		Data: *decoded,
	}, nil
}

func (c *DataStorage) LogTriggerDynamicEventLog(
	chainSelector uint64,
	filterName string,
	filters []DynamicEventFilters,
	opts *bindings.LogTriggerOptions,
) (cre.Trigger[*solana.Log, *bindings.DecodedLog[DynamicEvent]], error) {
	subkeys, err := c.Codec.EncodeDynamicEventSubkeys(filters)
	if err != nil {
		return nil, fmt.Errorf("failed to encode subkeys for DynamicEvent: %w", err)
	}

	req := &solana.FilterLogTriggerRequest{
		Name:            filterName,
		Address:         ProgramID.Bytes(),
		EventName:       "DynamicEvent",
		ContractIdlJson: []byte(IDL),
		Subkeys:         subkeys,
	}
	if opts != nil && opts.CpiFilterConfig != nil {
		req.CpiFilterConfig = opts.CpiFilterConfig
	}

	rawTrigger := solana.LogTrigger(chainSelector, req)
	return &DynamicEventTrigger{
		Trigger:  rawTrigger,
		contract: c,
	}, nil
}

// NoFieldsFilters holds optional filter values for NoFields log triggers.
type NoFieldsFilters struct{}

func (c *Codec) EncodeNoFieldsSubkeys(filters []NoFieldsFilters) ([]*solana.SubkeyConfig, error) {
	_ = filters
	subkeys := make([]*solana.SubkeyConfig, 0)
	return subkeys, nil
}

type NoFieldsTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
	contract *DataStorage
}

func (t *NoFieldsTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[NoFields], error) {
	decoded, err := ParseEvent_NoFields(l.GetData())
	if err != nil {
		return nil, fmt.Errorf("failed to decode NoFields log: %w", err)
	}
	return &bindings.DecodedLog[NoFields]{
		Log:  l,
		Data: *decoded,
	}, nil
}

func (c *DataStorage) LogTriggerNoFieldsLog(
	chainSelector uint64,
	filterName string,
	filters []NoFieldsFilters,
	opts *bindings.LogTriggerOptions,
) (cre.Trigger[*solana.Log, *bindings.DecodedLog[NoFields]], error) {
	subkeys, err := c.Codec.EncodeNoFieldsSubkeys(filters)
	if err != nil {
		return nil, fmt.Errorf("failed to encode subkeys for NoFields: %w", err)
	}

	req := &solana.FilterLogTriggerRequest{
		Name:            filterName,
		Address:         ProgramID.Bytes(),
		EventName:       "NoFields",
		ContractIdlJson: []byte(IDL),
		Subkeys:         subkeys,
	}
	if opts != nil && opts.CpiFilterConfig != nil {
		req.CpiFilterConfig = opts.CpiFilterConfig
	}

	rawTrigger := solana.LogTrigger(chainSelector, req)
	return &NoFieldsTrigger{
		Trigger:  rawTrigger,
		contract: c,
	}, nil
}
