// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains log trigger bindings for events defined in the IDL.

package data_storage

import (
	"fmt"

	solanago "github.com/gagliardetto/solana-go"
	solana "github.com/smartcontractkit/cre-sdk-go/capabilities/blockchain/solana"
	bindings "github.com/smartcontractkit/cre-sdk-go/capabilities/blockchain/solana/bindings"
	cre "github.com/smartcontractkit/cre-sdk-go/cre"
)

var (
	_ = solana.FilterLogTriggerRequest{}
	_ = bindings.LogTriggerOptions{}
	_ = bindings.DecodedLog[struct{}]{}
)

// Events
// The <Event>Filters struct should be used as a filter for log triggers.
// Only top-level scalar fields with supported subkey encodings are auto-filterable.
// Nested structs, vecs, arrays, bool, u128, and i128 require manual SubkeyConfig.

// AccessLoggedFilters holds optional filter values for AccessLogged log triggers.
// Set a field to filter on that value (OR across filter rows). Leave nil for wildcard.
type AccessLoggedFilters struct {
	Caller  *solanago.PublicKey
	Message *string
}

func (c *Codec) EncodeAccessLoggedSubkeys(filters []AccessLoggedFilters) ([]*solana.SubkeyConfig, error) {
	CallerComparers := make([]*solana.ValueComparator, 0)
	MessageComparers := make([]*solana.ValueComparator, 0)

	for _, f := range filters {
		if f.Caller != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Caller)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Caller: %w", err)
			}
			CallerComparers = append(CallerComparers, &solana.ValueComparator{
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
				Value:    val,
			})
		}
		if f.Message != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Message)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Message: %w", err)
			}
			MessageComparers = append(MessageComparers, &solana.ValueComparator{
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
				Value:    val,
			})
		}
	}

	subkeys := make([]*solana.SubkeyConfig, 0)
	if len(CallerComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Comparers: CallerComparers,
			Path:      []string{"Caller"},
		})
	}
	if len(MessageComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Comparers: MessageComparers,
			Path:      []string{"Message"},
		})
	}
	return subkeys, nil
}

// AccessLoggedTrigger wraps the raw log trigger and provides decoded AccessLogged data.
type AccessLoggedTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
}

// Adapt decodes the log into AccessLogged event data.
func (t *AccessLoggedTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[AccessLogged], error) {
	decoded, err := ParseEvent_AccessLogged(l.GetData())
	if err != nil {
		return nil, fmt.Errorf("failed to decode AccessLogged log: %w", err)
	}
	return &bindings.DecodedLog[AccessLogged]{
		Data: *decoded,
		Log:  l,
	}, nil
}

// LogTriggerAccessLoggedLog registers a typed log trigger for AccessLogged events.
func (c *DataStorage) LogTriggerAccessLoggedLog(
	chainSelector uint64,
	filterName string,
	filters []AccessLoggedFilters,
	opts *bindings.LogTriggerOptions,
) (cre.Trigger[*solana.Log, *bindings.DecodedLog[AccessLogged]], error) {
	subkeys, err := c.Codec.EncodeAccessLoggedSubkeys(filters)
	if err != nil {
		return nil, fmt.Errorf("failed to encode subkeys for AccessLogged: %w", err)
	}
	req := &solana.FilterLogTriggerRequest{
		Address:         ProgramID.Bytes(),
		ContractIdlJson: []byte(IDL),
		EventName:       "AccessLogged",
		Name:            filterName,
		Subkeys:         subkeys,
	}
	if opts != nil && opts.CPI {
		req.CpiFilterConfig = bindings.AnchorCPILogTriggerConfig(ProgramID.Bytes())
	}
	rawTrigger := solana.LogTrigger(chainSelector, req)
	return &AccessLoggedTrigger{Trigger: rawTrigger}, nil
}

// DynamicEventFilters holds optional filter values for DynamicEvent log triggers.
// Set a field to filter on that value (OR across filter rows). Leave nil for wildcard.
type DynamicEventFilters struct {
	Key      *string
	Sender   *string
	Metadata *[]byte
}

func (c *Codec) EncodeDynamicEventSubkeys(filters []DynamicEventFilters) ([]*solana.SubkeyConfig, error) {
	KeyComparers := make([]*solana.ValueComparator, 0)
	SenderComparers := make([]*solana.ValueComparator, 0)
	MetadataComparers := make([]*solana.ValueComparator, 0)

	for _, f := range filters {
		if f.Key != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Key)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Key: %w", err)
			}
			KeyComparers = append(KeyComparers, &solana.ValueComparator{
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
				Value:    val,
			})
		}
		if f.Sender != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Sender)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Sender: %w", err)
			}
			SenderComparers = append(SenderComparers, &solana.ValueComparator{
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
				Value:    val,
			})
		}
		if f.Metadata != nil {
			val, err := bindings.PrepareSubkeyValue(*f.Metadata)
			if err != nil {
				return nil, fmt.Errorf("failed to encode subkey value for Metadata: %w", err)
			}
			MetadataComparers = append(MetadataComparers, &solana.ValueComparator{
				Operator: solana.ComparisonOperator_COMPARISON_OPERATOR_EQ,
				Value:    val,
			})
		}
	}

	subkeys := make([]*solana.SubkeyConfig, 0)
	if len(KeyComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Comparers: KeyComparers,
			Path:      []string{"Key"},
		})
	}
	if len(SenderComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Comparers: SenderComparers,
			Path:      []string{"Sender"},
		})
	}
	if len(MetadataComparers) > 0 {
		subkeys = append(subkeys, &solana.SubkeyConfig{
			Comparers: MetadataComparers,
			Path:      []string{"Metadata"},
		})
	}
	return subkeys, nil
}

// DynamicEventTrigger wraps the raw log trigger and provides decoded DynamicEvent data.
type DynamicEventTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
}

// Adapt decodes the log into DynamicEvent event data.
func (t *DynamicEventTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[DynamicEvent], error) {
	decoded, err := ParseEvent_DynamicEvent(l.GetData())
	if err != nil {
		return nil, fmt.Errorf("failed to decode DynamicEvent log: %w", err)
	}
	return &bindings.DecodedLog[DynamicEvent]{
		Data: *decoded,
		Log:  l,
	}, nil
}

// LogTriggerDynamicEventLog registers a typed log trigger for DynamicEvent events.
func (c *DataStorage) LogTriggerDynamicEventLog(
	chainSelector uint64,
	filterName string,
	filters []DynamicEventFilters,
	opts *bindings.LogTriggerOptions,
) (cre.Trigger[*solana.Log, *bindings.DecodedLog[DynamicEvent]], error) {
	subkeys, err := c.Codec.EncodeDynamicEventSubkeys(filters)
	if err != nil {
		return nil, fmt.Errorf("failed to encode subkeys for DynamicEvent: %w", err)
	}
	req := &solana.FilterLogTriggerRequest{
		Address:         ProgramID.Bytes(),
		ContractIdlJson: []byte(IDL),
		EventName:       "DynamicEvent",
		Name:            filterName,
		Subkeys:         subkeys,
	}
	if opts != nil && opts.CPI {
		req.CpiFilterConfig = bindings.AnchorCPILogTriggerConfig(ProgramID.Bytes())
	}
	rawTrigger := solana.LogTrigger(chainSelector, req)
	return &DynamicEventTrigger{Trigger: rawTrigger}, nil
}

// NoFieldsFilters holds optional filter values for NoFields log triggers.
// Set a field to filter on that value (OR across filter rows). Leave nil for wildcard.
type NoFieldsFilters struct{}

func (c *Codec) EncodeNoFieldsSubkeys(filters []NoFieldsFilters) ([]*solana.SubkeyConfig, error) {
	subkeys := make([]*solana.SubkeyConfig, 0)
	return subkeys, nil
}

// NoFieldsTrigger wraps the raw log trigger and provides decoded NoFields data.
type NoFieldsTrigger struct {
	cre.Trigger[*solana.Log, *solana.Log]
}

// Adapt decodes the log into NoFields event data.
func (t *NoFieldsTrigger) Adapt(l *solana.Log) (*bindings.DecodedLog[NoFields], error) {
	decoded, err := ParseEvent_NoFields(l.GetData())
	if err != nil {
		return nil, fmt.Errorf("failed to decode NoFields log: %w", err)
	}
	return &bindings.DecodedLog[NoFields]{
		Data: *decoded,
		Log:  l,
	}, nil
}

// LogTriggerNoFieldsLog registers a typed log trigger for NoFields events.
func (c *DataStorage) LogTriggerNoFieldsLog(
	chainSelector uint64,
	filterName string,
	filters []NoFieldsFilters,
	opts *bindings.LogTriggerOptions,
) (cre.Trigger[*solana.Log, *bindings.DecodedLog[NoFields]], error) {
	subkeys, err := c.Codec.EncodeNoFieldsSubkeys(filters)
	if err != nil {
		return nil, fmt.Errorf("failed to encode subkeys for NoFields: %w", err)
	}
	req := &solana.FilterLogTriggerRequest{
		Address:         ProgramID.Bytes(),
		ContractIdlJson: []byte(IDL),
		EventName:       "NoFields",
		Name:            filterName,
		Subkeys:         subkeys,
	}
	if opts != nil && opts.CPI {
		req.CpiFilterConfig = bindings.AnchorCPILogTriggerConfig(ProgramID.Bytes())
	}
	rawTrigger := solana.LogTrigger(chainSelector, req)
	return &NoFieldsTrigger{Trigger: rawTrigger}, nil
}
