// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.
// Code generated by https://github.com/smartcontractkit/cre-cli. DO NOT EDIT.

package data_storage

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
	solana "github.com/smartcontractkit/cre-sdk-go/capabilities/blockchain/solana"
	cre "github.com/smartcontractkit/cre-sdk-go/cre"
	"math/big"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_DataAccount:
		value := new(DataAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as DataAccount: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_DataAccount(accountData []byte) (*DataAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_DataAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_DataAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(DataAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type DataAccount: %w", err)
	}
	return acc, nil
}

func (c *Codec) DecodeDataAccount(data []byte) (*DataAccount, error) {
	return ParseAccount_DataAccount(data)
}

func (c *DataStorage) ReadAccount_DataAccount(
	runtime cre.Runtime,
	accountAddress solanago.PublicKey,
	blockNumber *big.Int,
) cre.Promise[*DataAccount] {
	// cre account read
	bn := cre.PromiseFromResult(uint64(blockNumber.Int64()), nil)
	promise := cre.ThenPromise(bn, func(bn uint64) cre.Promise[*solana.GetAccountInfoWithOptsReply] {
		return c.client.GetAccountInfoWithOpts(runtime, &solana.GetAccountInfoWithOptsRequest{
			Account: accountAddress.Bytes(),
			Opts:    &solana.GetAccountInfoOpts{MinContextSlot: bn},
		})
	})
	return cre.Then(promise, func(response *solana.GetAccountInfoWithOptsReply) (*DataAccount, error) {
		return ParseAccount_DataAccount(response.Value.Data.GetRaw())
	})
}
